/*
 * ModemConfigFile.cpp - where the modem's direwolf.conf lives.
 *
 * This file is part of AX25Chat.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "ModemConfigFile.h"
#include "AppConfig.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QStandardPaths>
#include <QTemporaryFile>
#include <QRegularExpression>
#include <QTextStream>

namespace modemconf {

QString userPath()
{
    return QDir(AppConfig::configDir()).filePath(QStringLiteral("direwolf.conf"));
}

bool directoryIsWritable(const QString &directory)
{
    if (!QFileInfo(directory).isDir()) return false;
    QTemporaryFile probe(QDir(directory).filePath(QStringLiteral(".ax25chat-XXXXXX")));
    return probe.open();
}

QString writeStarter(const QString &pathIn, const QString &callsign, QString *error)
{
    QString path = pathIn;
    if (QFileInfo::exists(path)) return path;

    QString directory = QFileInfo(path).absolutePath();
    if (!directoryIsWritable(directory)) {
        QDir().mkpath(directory);
        if (!directoryIsWritable(directory)) {
            path = userPath();
            directory = QFileInfo(path).absolutePath();
        }
    }
    if (!QDir().mkpath(directory)) {
        if (error) *error = QStringLiteral("Cannot create %1").arg(directory);
        return QString();
    }

#ifdef Q_OS_WIN
    const QString ptt = QStringLiteral("#PTT      COM3 RTS");
#else
    const QString ptt = QStringLiteral("#PTT      /dev/ttyUSB0 RTS");
#endif
    const QString text = QStringLiteral(
        "# direwolf.conf written by AX25Chat.\n"
        "# Full reference: the User Guide shipped with Dire Wolf.\n"
        "\n"
        "# Audio device. 0 is the first one; on Linux \"plughw:1,0\" style names work too.\n"
        "ADEVICE  0\n"
        "CHANNEL  0\n"
        "MYCALL   %1\n"
        "\n"
        "# 1200 baud AFSK is standard on VHF packet and APRS.\n"
        "MODEM    1200\n"
        "\n"
        "# Transmit keying. VOX adds a release delay that collides with the next\n"
        "# station, so a real PTT line is strongly preferred on packet.\n"
        "%2\n").arg(callsign.isEmpty() ? QStringLiteral("NOCALL") : callsign, ptt);

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error) *error = file.errorString();
        return QString();
    }
    file.write(text.toUtf8());
    if (!file.commit()) {
        if (error) *error = file.errorString();
        return QString();
    }
    return path;
}

QString writeGenerated(const QString &path, const QString &callsign, int speed, const QString &ptt,
                       int gpio, QString *error)
{
    const QString directory = QFileInfo(path).absolutePath();
    if (!QDir().mkpath(directory)) {
        if (error) *error = QStringLiteral("Cannot create %1").arg(directory);
        return QString();
    }
    QString pttLine;
    if (ptt == QLatin1String("cm108")) pttLine = QStringLiteral("PTT      CM108 %1").arg(gpio);
    else if (ptt == QLatin1String("rts")) pttLine = QStringLiteral("PTT      /dev/ttyUSB0 RTS");
    else if (ptt == QLatin1String("dtr")) pttLine = QStringLiteral("PTT      /dev/ttyUSB0 DTR");
    else pttLine = QStringLiteral("# No PTT line: the radio's VOX keys the transmitter.");

    const QString text = QStringLiteral(
        "# direwolf.conf generated by AX25Chat from the Configuration page.\n"
        "# Rewritten on every save; edit the choices there, not this file.\n"
        "\n"
        "ADEVICE  default\n"
        "ARATE    48000\n"
        "CHANNEL  0\n"
        "MYCALL   %1\n"
        "MODEM    %2\n"
        "%3\n").arg(callsign.isEmpty() ? QStringLiteral("NOCALL") : callsign).arg(speed).arg(pttLine);

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error) *error = file.errorString();
        return QString();
    }
    file.write(text.toUtf8());
    if (!file.commit()) {
        if (error) *error = file.errorString();
        return QString();
    }
    return path;
}

QString defaultFile()
{
    QStringList candidates;
#ifdef Q_OS_WIN
    candidates << QDir::home().filePath(QStringLiteral("direwolf.conf"));
#endif
    candidates << userPath()
               << QDir::home().filePath(QStringLiteral("direwolf.conf"))
               << QDir::home().filePath(QStringLiteral(".direwolf/direwolf.conf"))
               << QStringLiteral("/etc/direwolf.conf");
#ifdef Q_OS_WIN
    candidates << QStringLiteral("C:\\Program Files\\Direwolf\\direwolf.conf");
#endif
    for (const QString &path : candidates) {
        if (QFileInfo(path).isFile()) return path;
    }
    return QString();
}

QList<int> channelsIn(const QString &path)
{
    QList<int> channels;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) return channels;
    QTextStream in(&file);
    while (!in.atEnd()) {
        const QString line = in.readLine().trimmed();
        if (line.startsWith('#')) continue;
        const QStringList words = line.split(QRegularExpression(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
        if (words.size() >= 2 && words.at(0).compare(QStringLiteral("CHANNEL"), Qt::CaseInsensitive) == 0) {
            bool ok = false;
            const int n = words.at(1).toInt(&ok);
            if (ok && !channels.contains(n)) channels << n;
        }
    }
    return channels;
}

} // namespace modemconf
